openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: User created successfully
        '400':
          description: Invalid input data
      tags:
        - Users

components:
  schemas:
    UserRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
          description: Name of the user
          maxLength: 255
        email:
          type: string
          description: Email of the user
          maxLength: 255
