ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
    database:
        name: "sample_kotlin_app"
        url: "jdbc:mysql://localhost:3306/sample_kotlin_app"
        user: "root"
        password: "password"
