ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
    database:
        name: "sample_kotlin_app"
        url: ""
        user: "root"
        password: "password"
